### ISSUE TITLE
abandonned package ?

### ISSUE THREAD

**Issue by spipu** [BeezUP/api-php-client#8]
I see that this package has not been really updated since 2 years, but the official beezup api doc https://api-docs.beezup.com/ has some new end-point (order V3 for example).

This package is abandoned ? Or it will be updated ?

**Comment by JohnnyMaxK** [comment]
Good question @spipu I'm going to ask to our specialist @lferrerraventos

**Comment by spipu** [comment]
Hi, do we have some news ?

**Comment by lferrerraventos** [comment]
This lib has been generated using swagger client with the swagger spec: https://api-docs.beezup.com/swagger.json
The package is still being used by some other modules, anyway you can always generate it, what is most important is the swagger spec, not the generated code.
Please refer to the following repo to use swagger code gen:
https://github.com/swagger-api/swagger-codegen
